# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fccfefba6e4a9c61d7c8f7c1568a19c1ecaeec2310d88e6807f5c05ba7ecdfa632b116d3b9f29248592c826aef188d121f2efed9bf9c8850bccbd0967f03c11a

test:
  secret_key_base: 232e395898a9fb365f724bff638b2f34f2f2e1d4d8591c38ea3dfe303292c5cf8a9511add662ecc88e9cd3463360d7b258710eac826ec8ae6c0fcc7f6dae7a88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
